apiVersion: v1
kind: Secret
metadata:
  name: dev-db-app-secret
  namespace: paas-databases
type: kubernetes.io/basic-auth
stringData:
  username: app
  password: changeme-in-production   # use a real secret manager for prod