apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg-operator
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/foyez/paas-platform
    targetRevision: HEAD
    path: k8s/cnpg-operator

  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system

  # No syncPolicy = manual sync only
  # ArgoCD will detect drift but NOT apply it automatically
